### ISSUE TITLE
Pull Requests

### ISSUE THREAD

**Issue by ghost** [androidrbox/RboxFireTvMods#10]
Sorry for the mess. i'm new to this thing. but i think the whole thing should still become clear, if you want to take them.

**Comment by androidrbox** [comment]
Thanks!  It is a bit of a mess, one of them actually includes all of them, and it looks like you left off the .java on a few of the files, but I'll figure it out.  Probably wind up just cherry-picking the commits from your repo instead of merging the pull requests to make it easier.  Unfortunately I don't have a lot of time to work on this right now, so I'll leave this and the pull requests open and when I have some more time, I'll take a look at them and let you know if I have any questions.

**Comment by ghost** [comment]
I used the webinterface and didn't notice github creating a patch branch for every commit and at the end creating a pull request for the whole master -.- I also think the best way is to cherry pick my changes the way how you want them if so. For the current pull requests i think i remove them, this way i also can clean up my branches. Should git from android studio in the future, this way i can create more changes per commit accordingly. Sorry again and thanks for the .java hint!... 

No problem, you don't have time to look into this at the moment. I just keep doing my stuff on my master, try to fix the module and so on. 

One last thing. In the CreateMenu class i changed some strings and moved the settings item back to the old place, would have done a commit for this but forgot it and ended up uploading the whole new file instead.

And thanks for your stuff and effort!
